### ISSUE TITLE
Feedback from@daz

### ISSUE THREAD

**Issue by dangershony** [stratisproject/Breeze#138] opened 2017-06-30 22:25 UTC
1) Nice job, looks great :slightly_smiling_face:    2) After entering the password would be nice to be able to hit enter rather than going back to the mouse.     3) for some reason if i'm "in" usa i get 0-1 connections and uk i get 8.    4) everytime i click on the recieve address now i get the same address, an option to get a new address would be nice. The first 3 times it changed it, now it seems stuck even with a restart.   4) since i've sent the 1 tbtc it hasnt updated any further, seem to be stuck with unconfirmed balance, though guessing the nodes are busy and it will just take longer than it did at the start?

**Comment by dangershony** [comment] 2017-06-30 23:00
Ok so firstly great wallet, love how simple it is, definitely user friendly and looking forward to seeing stratis on the left :slightly_smiling_face:
I know this is still early days and just for testing, but a few things i've thought when using it - 
1) Would be nice to be able to hit the enter key rather than having to go back to the mouse to login and send (i keep automatically doing it)
2) An option for a new address on "recieve" would be good, i keep getting the same address and seems random on when it gives me a new one
Also maybe an ability to set a new name for each one so the history is organised
3) A copy button for the transaction i.d - or a link straight to the block explorer (though i imagine this will come anyway on mainnet)
4) Obvs would like to know how much of a fee i'm going to get charged before sending
5) An option to take the fee from amount, and to send max balance
6) Confirmation of sending
7) Notification of recieving

**Comment by STRATISdaz** [comment] 2017-06-30 23:35
I can't seem to spend my unconfirmed balance. Have 0 on active, but 14.5 on unconfirmed. Clicking on send does nothing.

**Comment by STRATISdaz** [comment] 2017-06-30 23:40
Also 8) an option to change your password or account name

**Comment by STRATISdaz** [comment] 2017-06-30 23:44
Pervious issue may be the fact that i'm behind on syncing. Stuck on 99%, 1150336 out of 1150366. Closing the wallet and reopening doesn't fix the issue

**Comment by STRATISdaz** [comment] 2017-07-01 00:01
After closing the wallet and checking taskmanager I had 5 dotnet processes running. Closing these and restarting the wallet fixed the stalling issue

**Comment by STRATISdaz** [comment] 2017-07-01 00:04
Am still only able to spend my active balance, not my unconfirmed.

Also 9) Can't right click the mouse to paste an address, only ctl V

**Comment by STRATISdaz** [comment] 2017-07-01 00:18
![image](https://user-images.githubusercontent.com/29806805/27757581-1664184e-5dfb-11e7-87a5-07c0584f6e8b.png)
When sending to myself (wanted to try spending unconfirmed balance again) the transaction has shown up multiple times as sent

**Comment by STRATISdaz** [comment] 2017-07-01 00:31
After opening and closing a second instance of my wallet I had a message saying the API had crashed and to restart wallet. The wallet then showed no transaction history. After closing and restarting I got a blank pop up
![image](https://user-images.githubusercontent.com/29806805/27757711-0142f19a-5dfd-11e7-8df7-6b702519826f.png)

**Comment by STRATISdaz** [comment] 2017-07-01 00:33
Restarted and history has returned and wallet seems ok. But opening a second wallet again causes the same issue 
![image](https://user-images.githubusercontent.com/29806805/27757731-5668affc-5dfd-11e7-91bf-81704d888c13.png)

**Comment by STRATISdaz** [comment] 2017-07-01 00:34
The above popup needs ok'ing 3 times before it goes

**Comment by STRATISdaz** [comment] 2017-07-01 00:50
Ok this might be what killed it the first time. Seemed ok and fully synced for a while but has now dropped to 99% and showing me behind. 
![image](https://user-images.githubusercontent.com/29806805/27757867-7461bfd8-5dff-11e7-8993-ea9d1e315c59.png)
Task manager shows 4 dotnet processes running

**Comment by STRATISdaz** [comment] 2017-07-01 01:16
Ok so wallet is showing fully synced, but balance still unconfirmed from 01.02 (time is now 02.15) And I also can't send 0.01 tbtc out (pressing send does nothing)
![image](https://user-images.githubusercontent.com/29806805/27758023-2e5bc12e-5e03-11e7-843f-2397b9e8fd6c.png)
Gonna have a nap and see if it is confirmed when I wake

**Comment by STRATISdaz** [comment] 2017-07-01 04:39
05:37 - wallet showing as fully synced but balance still unconfirmed 
![image](https://user-images.githubusercontent.com/29806805/27759122-98047eb0-5e1f-11e7-9538-35837f77f5a6.png)

**Comment by STRATISdaz** [comment] 2017-07-01 04:44
Closed wallet, task manager shows no electron or dotnet running. Restarted and shows one of each as normal. wallet shows 100% with 8 connections but balance still unconfirmed

**Comment by STRATISdaz** [comment] 2017-07-01 04:46
Successfully sent 0.001 to another address. Now 0 active balance

**Comment by STRATISdaz** [comment] 2017-07-01 05:50
Wallet appears to be processing blocks ok, now 100% 1150601 blocks processed. Transaction still unconfirmed. will request some coins on the slack and see if it is that which fixed it last time

**Comment by STRATISdaz** [comment] 2017-07-01 06:31
Used faucet just now - on block 1150621. Coins added to unconfirmed instantly, Will wait and see if it confirms now

**Comment by STRATISdaz** [comment] 2017-07-01 06:37
4.78 tbtc just confirmed - 14.9 still unconfirmed.

**Comment by STRATISdaz** [comment] 2017-07-01 06:56
Restarted wallet again and still shows in unconfirmed. May have got it stuck. for the transaction details for the 14.2 it shows # as the block and each one has a different transaction I.D, which don't show up on the block explorer. Don't think it liked me sending them to myself :p

**Comment by STRATISdaz** [comment] 2017-07-01 12:46
I've had the blank one too, seems to be popping up randomly for a lot of people. Haven't worked out what's causing it.

**Comment by STRATISdaz** [comment] 2017-07-01 15:30
10) the loading screen should be something pretty and WOW

Transactions are still unconfirmed, I think I've officially locked those coins up

**Comment by STRATISdaz** [comment] 2017-07-01 15:40
When trying to send 0.0000000000001 and reducing the 0's each time till it sends I get:
![image](https://user-images.githubusercontent.com/29806805/27763459-e9921b46-5e7b-11e7-8391-5aacdcdf2261.png)

**Comment by STRATISdaz** [comment] 2017-07-01 15:40
clicking ok shows:
![image](https://user-images.githubusercontent.com/29806805/27763462-fbb41130-5e7b-11e7-917a-c322c73baeb2.png)

**Comment by STRATISdaz** [comment] 2017-07-01 15:41
one more warning after which I didn't screenshot
was for sending the amount - 0.00000001.
Trying again gives me two of the error messages

**Comment by STRATISdaz** [comment] 2017-07-01 15:42
and again gives me one

**Comment by STRATISdaz** [comment] 2017-07-01 15:45
Ok I now seem to get that error message everytime now when trying to send, with any amount

**Comment by STRATISdaz** [comment] 2017-07-01 15:46
Same happens with sending to another address
![image](https://user-images.githubusercontent.com/29806805/27763515-e025bd78-5e7c-11e7-9e8c-e141995a89f0.png)

**Comment by STRATISdaz** [comment] 2017-07-01 15:50
Restarted wallet and trying to send gives me
![image](https://user-images.githubusercontent.com/29806805/27763546-5ddd3e58-5e7d-11e7-84ce-6fd3bda01d9a.png)

**Comment by STRATISdaz** [comment] 2017-07-01 15:55
Closing the wallet and killing dotnet also doesn't fix the issue. Think I've broke it even more :p 
Also wallet is showing 0 connections, and I have just under 100 tbtc in my unconfirmed which isn't shown in history and nobody has mentioned they have sent me
![image](https://user-images.githubusercontent.com/29806805/27763586-0251722e-5e7e-11e7-915f-4b7501919586.png)
P.s hope i'm being helpful and not just annoying and spammy :D

**Comment by STRATISdaz** [comment] 2017-07-01 16:28
Anyways i'm done now as think i've officially killed my wallet.
My incoming balance is all stuck in unconfirmed, i have 0 connections and trying to send gives me error messages. restarting and killing dotnet doesn't solve. Has been like this for over 30 mins.

**Comment by dangershony** [comment] 2017-07-01 22:16
Hi thanks a lot this is very valuable we will probably add some of the issues as bugs to the next sprint

**Comment by STRATISdaz** [comment] 2017-07-01 23:25
Ok great, Sorry if my idea of breaking it wasn't what you hoped for, but felt like I succeeded. Glad to be of service. Let me know if any of my files are needed. Guessing I shouldn't move them elsewhere and see if the issues should be replicated? (or is there smarter ways of discovering the bugs?)

**Comment by bokobza** [comment] 2017-07-03 09:56
Thanks for the feedback @STRATISdaz :raising_hand:

**Comment by STRATISdaz** [comment] 2017-07-03 13:18
No worries, hope it helps :D

**Comment by dev0tion** [comment] 2017-07-04 10:10
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] focus on "decrypt" button](https://trello.com/c/61tkeGhw/90-wallet-gui-focus-on-decrypt-button)

**Comment by dev0tion** [comment] 2017-07-04 10:11
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Copy button for transaction ID](https://trello.com/c/URFnGux2/91-wallet-gui-copy-button-for-transaction-id)

**Comment by dev0tion** [comment] 2017-07-04 10:12
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet] Add "max" function to API](https://trello.com/c/VxsOrqcX/89-wallet-add-max-function-to-api)

**Comment by dev0tion** [comment] 2017-07-04 10:13
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Confirmation of sending](https://trello.com/c/CZifnwgL/92-wallet-gui-confirmation-of-sending)

**Comment by dev0tion** [comment] 2017-07-04 10:14
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Add native notifications](https://trello.com/c/Bt4u4OcC/88-wallet-gui-add-native-notifications)

**Comment by dev0tion** [comment] 2017-07-04 10:15
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Right click to copy/paste](https://trello.com/c/rdDyVnfs/93-wallet-gui-right-click-to-copy-paste)

**Comment by dev0tion** [comment] 2017-07-04 10:16
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Blank pop-up](https://trello.com/c/rHyT3AsS/94-wallet-gui-blank-pop-up)

**Comment by dev0tion** [comment] 2017-07-07 11:54
1) Done in #150 
2) It does not change randomly. You only get a new receive address when the previous address has a balance in it. This behaviour will not change, but we may add a "get new address" button in the future.
3) Done in #155 
4) This will be added in the next sprint, currently it's a set value, but we're working on fee estimations.
5) Being worked on
6) This will be added in the current sprint
7) Native notifications are planned in an upcoming sprint.
8) Might be added in the future, not planned currently
9) Fixed in #156

**Comment by STRATISdaz** [comment] 2017-07-14 23:14
Brilliant :) Thankyou for the update

**Closed** 2017-09-22 13:17 UTC
Labels: API, UI
