### ISSUE TITLE
Multiple transaction boxes

### ISSUE THREAD

**Issue by chrisradu** [stratisproject/Breeze#175] opened 2017-07-16 16:19 UTC
There are several transaction boxes appearing in the transaction history after making a 7 tbtc payment. They all have the same tx id and the same date.

![image](https://user-images.githubusercontent.com/24313609/28249292-7d1021d4-6a5b-11e7-9202-6cbca8808ab1.png)

SYSTEM DETAILS: Windows 7 Pro, 32-bit

**Comment by Neurosploit** [comment] 2017-07-16 17:05
This happens when you have a transaction from multiple inputs. I now have the same issue. See: https://www.blocktrail.com/tBTC/tx/b93b9c56a9316784f79fca0abff10618c830ca17f42f34f0e20dc18e1a424a30

I can now easily reproduce it probably since I have it in my wallet. I'll see if I can create a test for it.

**Comment by Neurosploit** [comment] 2017-07-18 19:23
I'm working on filtering them out in the walletcontroller. Need to add some tests for this and PR. Going to do that later this week.

**Comment by bep42** [comment] 2017-07-30 18:23
In a near future we'll also implement a pagination to make it easier to use 👍

**Comment by bokobza** [comment] 2017-09-04 10:34
This has been fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/241

**Closed by bokobza** 2017-09-04 10:34 UTC
