### ISSUE TITLE
Some issues v0.1.0 alpha

### ISSUE THREAD

**Issue by matje123** [stratisproject/Breeze#146] opened 2017-07-03 08:58 UTC
Win 7 64-bit

1.

Copy the 12-words passphrase from the box

2.

Drop downlist with rounded corners

3.

Highlight the active page

4.
Wrong balance

First received 1.1
Then send 0.001

Wrong balance

Without screenshot

5.

Hit enter button to decrypt wallet instead clicking 'decrypt'

6.

Hide the send button when (unconfirmed)balance is zero

7.

Pimp up the loading screen when starting breeze is possible.

Instead of 'loading', try a slider so it is clear the wallet is loading.

8.
Show the wallet name of the selected wallet in the top right corner.

![breeze1](https://user-images.githubusercontent.com/29857869/27785650-93cd8344-5fde-11e7-99a2-b5d53a013276.jpg)
![breeze2](https://user-images.githubusercontent.com/29857869/27785653-9663503e-5fde-11e7-92c0-61f59b3339b1.jpg)
![breeze3](https://user-images.githubusercontent.com/29857869/27785654-98ba263c-5fde-11e7-91ad-e12a760fdf96.jpg)
![breeze 4-1](https://user-images.githubusercontent.com/29857869/27785657-9a2adfb6-5fde-11e7-97e0-2cae602150d3.jpg)
![breeze4-2](https://user-images.githubusercontent.com/29857869/27785658-9bb8bbaa-5fde-11e7-863d-0f1f64a30b7c.jpg)

**Comment by bokobza** [comment] 2017-07-03 09:32
your wallet is behaving like a hen that lays golden eggs :-)
thanks for the feedback!

**Comment by matje123** [comment] 2017-07-03 09:33
Thanks, FYI i have created 2 wallets.

**Comment by bokobza** [comment] 2017-07-03 09:38
so you received 1.1 tbtc, sent 0.001 and your balance shows 2.1 tbtc.
do you have funds in your other wallet?

**Comment by matje123** [comment] 2017-07-03 09:40
There are funds yea, but i have the feeling it is also a bit messed up.

![breeze5](https://user-images.githubusercontent.com/29857869/27787251-6c7cb9da-5fe4-11e7-8842-7e72123cc483.jpg)

**Comment by bokobza** [comment] 2017-07-03 09:46
looks like it.
Would you mind sharing your wallet files with us? Don't worry there is no secret info there.
They're located in "%AppData%\StratisNode\bitcoin\TestNet" and have the extension ".wallet.json".
If you don't mind sharing them with me on Slack (if you're on Slack), that'd be much appreciated.
Thanks

**Comment by matje123** [comment] 2017-07-03 09:46
My balance of my second wallet with wrong balance did change a bit now:

![breeze6](https://user-images.githubusercontent.com/29857869/27787494-347a9632-5fe5-11e7-9a4e-52e325545c81.jpg)

**Comment by bokobza** [comment] 2017-07-03 09:46
added to Trello https://trello.com/c/vnS6fYsd/76-wrong-balance

**Comment by bokobza** [comment] 2017-07-03 09:47
yeah I guess transactions are getting confirmed

**Comment by matje123** [comment] 2017-07-03 09:51
Can i send them with email to?

**Comment by bokobza** [comment] 2017-07-03 10:05
sure send them to jeremy.bokobza@stratisplatform.com

**Comment by dev0tion** [comment] 2017-07-04 10:30
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] focus on "decrypt" button](https://trello.com/c/61tkeGhw/90-wallet-gui-focus-on-decrypt-button)

**Comment by dev0tion** [comment] 2017-07-04 10:30
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Highlight active page](https://trello.com/c/Xi1I3Jxj/98-wallet-gui-highlight-active-page)

**Comment by dev0tion** [comment] 2017-07-04 10:31
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Check payment amount](https://trello.com/c/oVBlpLQs/86-wallet-gui-check-payment-amount)

**Comment by dev0tion** [comment] 2017-07-07 12:04
Thanks a lot for the valuable feedback man! 

Here's where we stand: 
1) Done in #156 
2) Will be added in a future sprint, added to the backlog
3) Will be added in the current sprint
4) Jeremy is on it, will be fixed in this sprint
5) Done in #150 
6) Will be added in the current sprint 
7) Added to the backlog, will be dealt with in one of the next sprints
8) Not sure yet if we will be adding this.

**Closed by dev0tion** 2017-07-07 12:04 UTC
Labels: API, UI
